### PR TITLE
Fix plithnar

### LINKED ISSUE #15: Project-centric data model requested [Improvement]
Due to how users will be using project documents as a sighting scope for discovering transactions, the Elasticsearch index will need to be updated to reflect this. To achieve this, the Project document needs the following attributes which are currently on Transactions.
- Science Area
  - Full transition from Transaction to Project
- Institution
  - Full transition from Transaction to Project
- Instruments
  - Duplication of information. We will still want the instrument information on an individual transaction
- Instrument Groups
  - Duplication of information. We will still want the instrument group information on an individual transaction

### PR DESCRIPTION
**Pull request by dmlb2000**
### Description

Fix pull #17 to test and implement the requested schema changes.

### Issues Resolved

Fix #15 
### Check List

- [ ] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by dmlb2000** [comment]
@plithnar I'm getting a bad response from elasticsearch with your example query

```
b'{"error":{"root_cause":[{"type":"parsing_exception","reason":"Missing definition for aggregation [co_principal_investigator]","line":1,"col":289}],"type":"parsing_exception","reason":"Missing definition for aggregation [co_principal_investigator]","line":1,"col":289},"status":400}'
```

Do you know what the cause of this would be?

**Comment by plithnar** [comment]
@dmlb2000 Was my mistake, I had been cleaning up the test files to make them smaller and removed the filter definitions on the aggregations. I made an update to my fork and it should be reflected in the other pr

**Comment by dmlb2000** [comment]
@plithnar Can you verify both the queries and the schema are looking like what you want?

**Comment by plithnar** [comment]
Both issue_15_projects and issue_15_transactions have the aggregations "mis-labeled" (project3 aggregates co-pi's for example), but that shouldn't cause queries to fail. 
Aside from that, I noticed a large number of additional properties in the jsonschema files. That being said, the objects I added are still there so I believe that it should work as expected. The fields in particular which I am referring to are "additionalProperties", "created_date" and "updated_date".

**Comment by dmlb2000** [comment]
@plithnar Yes the addition of the `additionalProperties` property defines that extra object properties not defined in the `properties` property are not allowed.

So I'm going to take this as a, "it should work" answer, which is good enough for the second request.

@karcaw could you setup @plithnar with this branch on the MyEMSL development cluster? You'll need to rebuild the index using my branch see if it completes correctly, then @plithnar can have some real data to look at.

**Comment by karcaw** [comment]
it still doesent handle pushing the elastic search servers very much:

frontend:
```
Total Completed:  33%|██████████████████████████▋                                                     | 3/9 [02:12<06:25, 64.25s/it]
Traceback (most recent call last):█████▍                                                           | 27/217 [03:43<06:05,  1.92s/it]
  File "/opt/elasticsearch/bin/pacifica-elasticsearch", line 10, in <module>
    sys.exit(main())
  File "/opt/elasticsearch/lib/python3.6/site-packages/pacifica/elasticsearch/__main__.py", line 97, in main
    return args.func(args)
  File "/opt/elasticsearch/lib/python3.6/site-packages/pacifica/elasticsearch/search_sync.py", line 161, in search_sync
    return work_queue.progress(args)
  File "/opt/elasticsearch/lib/python3.6/site-packages/pacifica/elasticsearch/celery.py", line 56, in progress
    if not result.get():  # pragma: no cover failure testing is hard
  File "/opt/elasticsearch/lib/python3.6/site-packages/celery/result.py", line 226, in get
    on_message=on_message,
  File "/opt/elasticsearch/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 188, in wait_for_pending
    for _ in self._wait_for_pending(result, **kwargs):
  File "/opt/elasticsearch/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 255, in _wait_for_pending
    on_interval=on_interval):
  File "/opt/elasticsearch/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 56, in drain_events_until
    yield self.wait_for(p, wait, timeout=1)
  File "/opt/elasticsearch/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 65, in wait_for
    wait(timeout=timeout)
  File "/opt/elasticsearch/lib/python3.6/site-packages/celery/backends/rpc.py", line 63, in drain_events
    return self._connection.drain_events(timeout=timeout)
  File "/opt/elasticsearch/lib/python3.6/site-packages/kombu/connection.py", line 315, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/opt/elasticsearch/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
    return connection.drain_events(**kwargs)
  File "/opt/elasticsearch/lib/python3.6/site-packages/amqp/connection.py", line 500, in drain_events
    while not self.blocking_read(timeout):
  File "/opt/elasticsearch/lib/python3.6/site-packages/amqp/connection.py", line 505, in blocking_read
    frame = self.transport.read_frame()
  File "/opt/elasticsearch/lib/python3.6/site-packages/amqp/transport.py", line 252, in read_frame
    frame_header = read(7, True)
  File "/opt/elasticsearch/lib/python3.6/site-packages/amqp/transport.py", line 436, in _read
    s = recv(n - len(rbuf))
ConnectionResetError: [Errno 104] Connection reset by peer
```

backend:
```
Traceback (most recent call last):
  File "/opt/elasticsearch/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 232, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/opt/elasticsearch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/elasticsearch/lib/python3.6/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/elasticsearch/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/elasticsearch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/opt/elasticsearch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/elasticsearch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 279, in _read_status
    raise BadStatusLine(line)
```

**Comment by karcaw** [comment]
the index pacifica_elastic_04_09_2019 is now available.  I assume the main program loaded everything into celery before it crashed..

**Comment by plithnar** [comment]
@karcaw @dmlb2000 The new index looks great, but it seems like the instrument groups on transactions are missing.

**Comment by dmlb2000** [comment]
@karcaw Could you update and rerun the index?

**Comment by karcaw** [comment]
i have re-run.  same crash on the main process. @plithnar have another look

**Comment by plithnar** [comment]
@karcaw @dmlb2000 Instrument groups now there and looks great! Thanks guys!

**Pull request merged**
