### PR TITLE
Fix issue 23

### LINKED ISSUE #23: [Improvement] Add # Released
As a user, I would like to be able to filter project results based on the number of released transactions associated with it. Currently, there is no attribute to track this and so building a facet using the Searchkit API for this is impossible. 
I have been adding this as a UI count through a follow-on query for each project and looking at the total number of hits.

### PR DESCRIPTION
**Pull request by plithnar**
### Description

This will add the number of released datasets as an attribute of the project as requested by Millard

### Issues Resolved

Fix #23 

### Check List

- [ ] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by plithnar** [comment]
@dmlb2000 ping

**Comment by karcaw** [comment]
this seems to be only test files.

**Comment by plithnar** [comment]
@dmlb2000 Any status on this?

**Comment by dmlb2000** [comment]
@plithnar Okay I've gotten the released transaction count in there for projects, now it's back to stripping out required properties that aren't really required. The `long_name` is not an attribute of the instrument object.

**Comment by plithnar** [comment]
@dmlb2000, all unnecessary required properties stripped out I think, failure was inside "TestElasticsearch.test_main_celery"

**Comment by dmlb2000** [comment]
I'm wondering if we are waiting on this https://github.com/celery/celery/issues/5990

**Pull request merged**
