### PR TITLE
Fix #15 - Project-centric data model requested

### LINKED ISSUE #15: Project-centric data model requested [Improvement]
Due to how users will be using project documents as a sighting scope for discovering transactions, the Elasticsearch index will need to be updated to reflect this. To achieve this, the Project document needs the following attributes which are currently on Transactions.
- Science Area
  - Full transition from Transaction to Project
- Institution
  - Full transition from Transaction to Project
- Instruments
  - Duplication of information. We will still want the instrument information on an individual transaction
- Instrument Groups
  - Duplication of information. We will still want the instrument group information on an individual transaction

### PR DESCRIPTION
**Pull request by plithnar**
### Description

Updated Test schema to reflect the desired model layout. This is in an effort to link more data to the project itself and use the project as a sighting scope to then show a limited subset of transactions (datasets) that a user is interested in.

### Issues Resolved

Fixes #15 

### Check List

- [ ] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by dmlb2000** [comment]
@plithnar could you provide some jsonpaths for what should be considered mapped as keywords?

**Comment by plithnar** [comment]
@dmlb2000 I added the expected keyword for Science Theme. This was the only object I saw in the jsonschema files which was missing the keyword property.

**Comment by dmlb2000** [comment]
@plithnar I wasn't quite thinking about that but the addition is fine.

The elastic search mapping may need to be updated, what does that look lik

**Comment by plithnar** [comment]
@dmlb2000  I don't think the mapping (pacifica/elasticsearch/mapping.json) needs to be changed since all the objects had already been defined as a child of Transactions. Is there another file you need me to update besides the test jsonschemas so you have everything you need?

**Comment by dmlb2000** [comment]
@plithnar That was the answer I was hoping for, could you provide a sample query (something like https://github.com/pacifica/pacifica-elasticsearch/blob/master/tests/issue_9.json) that would utilize the data you are adding to the projects document?

**Comment by plithnar** [comment]
@dmlb2000 Added two test queries. Issue_15_projects.json is full query from the project standpoint, Issue_15_transactions.json is MOSTLY the full query. The only difference is a large number of the automatically linked key-value pair aggregations to keep from bloating that file

**Comment by dmlb2000** [comment]
This should be fixed by, #19

**Pull request closed without merging**
