### PR TITLE
Fix #22 Add Transactions Select Query

### LINKED ISSUE #22: transactionuser updates do not update transactions updated field, and as such an update scan will miss all changes
### Scenario:
trying to run pacifica-elasticsearch with a --time-ago "60 days".  The newly released transactions do not appear in the elastic search index.
database for transaction user:
```
 transaction_id |       created       |       updated       | deleted | user_id |           relationship_id            |                 uuid
----------------+---------------------+---------------------+---------+---------+--------------------------------------+--------------------------------------
1624717 | 2019-10-05 03:57:22 | 2019-10-05 03:57:22 |         |   47946 | be0cd1a7-2ab1-463d-9a3e-94b513ddd558 | a36567da-bcd7-44dc-b7ef-31548efb0a7a
```
but yet the transaction does not show an update:
```
   id    |       created       |       updated       | deleted | suspense_date | description
---------+---------------------+---------------------+---------+---------------+-------------
 1624717 | 2018-09-13 18:57:31 | 2018-10-06 05:23:29 |         |               |
```

and so the script passes over it.

### Expected Result:
transactions recently released should appear as released in the index

### Actual Result:
no changes get made.

### PR DESCRIPTION
**Pull request by dmlb2000**
### Description

This adds a custom select query to pull updated transactions based
on all dependent objects and their updated times.

Signed-off-by: David Brown <dmlb2000@gmail.com>

### Issues Resolved

Fix #22 
### Check List

- [ ] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by dmlb2000** [comment]
@karcaw That select query is crazy big, it would be nice to know the performance impact it has on a database with a million transactions.

**Comment by karcaw** [comment]
You don't have a benchmark in the test suite?

**Comment by dmlb2000** [comment]
@karcaw I have a script that allows me to benchmark the query yes. Though it's really pointless with the amount of data in the test suite. I've added the script I use in the `contrib` directory.

**Comment by dmlb2000** [comment]
@karcaw I finally got the pipeline to pass without changing the testing. I think there was a bug in the original implementation not being accurate with the paging/looping. There was a combination of an off by one and non-zero indexing when doing paging error.

**Review by karcaw — APPROVED** [review]
lgtm

**Review by karcaw — APPROVED** [review]

**Pull request merged**
